### ISSUE TITLE
兄弟你好，根据你的项目，做了一个对应的wechaty插件

### ISSUE THREAD

**Issue by gengchen528** [henryfanyiye/wechat-fanli-robot#1]
很高兴你能够分享返利机器人的源码，我根据你的项目做了一些调整和整合做了一个wechaty的插件版本，让wechaty的开发者能够更快的接入返利机器人  希望不要介意，这是项目地址https://github.com/gengchen528/wechaty-fanli

**Comment by henryfanyiye** [comment]
@gengchen528 很高兴这个demo的能对你起到帮助
